repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff lint
        entry: ruff check --ignore=E501
        language: system
        types: [python]

      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]

      - id: black
        name: black
        entry: black
        language: system
        types: [python]

      - id: pyright
        name: pyright
        entry: pyright --pythonversion 3.12
        language: system
        types: [python]

      - id: pytest
        name: pytest
        entry: pytest -q
        language: system
        pass_filenames: false
