name: instant-automerge
on:
  pull_request:
    types: [opened, ready_for_review]   # PR が開かれた／ドラフト解除されたら実行
permissions:
  contents: write       # マージに必要
  pull-requests: write
jobs:
  enable:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge_method: squash         # merge / rebase も可
          token: ${{ secrets.GITHUB_TOKEN }}
