# .github/workflows/instant-automerge.yml
name: instant-automerge

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash          # 好みで merge / rebase も可
          token: ${{ secrets.GITHUB_TOKEN }}
